packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.9.16'
  - '@turbo/darwin-arm64@2.9.16'
  - '@turbo/linux-64@2.9.16'
  - '@turbo/linux-arm64@2.9.16'
  - '@turbo/windows-64@2.9.16'
  - '@turbo/windows-arm64@2.9.16'
  - turbo@2.9.16
